# Generated by Django 6.0.2 on 2026-02-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hall_ticket_number", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science and Engineering"),
                            ("AIML", "Artificial Intelligence and Machine Learning"),
                            ("CYBER", "Cyber Security"),
                            ("ECE", "Electronics and Communication Engineering"),
                            ("EEE", "Electrical and Electronics Engineering"),
                            ("CIVIL", "Civil Engineering"),
                            ("MECH", "Mechanical Engineering"),
                            ("IT", "Information Technology"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        choices=[
                            ("2023-2027", "2023-27"),
                            ("2024-2028", "2024-28"),
                            ("2025-2029", "2025-29"),
                        ],
                        max_length=15,
                    ),
                ),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                (
                    "leetcode_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "codechef_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "hackerrank_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gfg_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
