# Generated by Django 6.0.2 on 2026-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_studentprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="codechef_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gfg_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="hackerrank_badges",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="leetcode_solved",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
