# Generated by Django 6.0.2 on 2026-02-25 09:44

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_studentprofile_codechef_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HackathonParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hackathon_name", models.CharField(max_length=255)),
                ("conducted_by", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("won", models.BooleanField(default=False)),
                (
                    "participation_certificate",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="participation_certificate"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Winner", "Winner"),
                            ("Runner up", "Runner up"),
                            ("Bronze", "Bronze"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "prize_money",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "project_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("domain", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "winning_certificate",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="winning_certificate",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hackathons",
                        to="profiles.studentprofile",
                    ),
                ),
            ],
        ),
    ]
