# Generated by Django 6.0.2 on 2026-02-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_hackathonparticipation"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="codechef_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gfg_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="hackerrank_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="leetcode_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="stats_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
